config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :affiliates
  root 'users#auth'
  get "users/auth"
  get "users/logout"
  post "users/check"

  get "statistics/index"
  get "statistics/get_data"
  post "statistics/create"

  get "users/toggle"
 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :manage, :all
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/affiliate.rb
class Affiliate < ActiveRecord::Base
	validates :name, presence: true
	belongs_to :company
	default_scope { order('name') }

end

app/models/company.rb
class Company < ActiveRecord::Base
	#validates :name, presense: true
	has_many :affiliates
end

app/models/installation.rb
class Installation < ActiveRecord::Base
	has_one :affiliate
end

app/models/statistic.rb
class Statistic < ActiveRecord::Base
	has_one :affiliate
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/affiliates_controller.rb
class AffiliatesController < ApplicationController

	def index
		if is_auth?
			@affiliates = Affiliate.where( is_deleted: false )
		else
			redirect_to :controller => 'users', :action => 'auth'
		end
	end

	def show

	end

	def new
		if is_auth?
			@companies = Company.all
			@affiliate = Affiliate.new
		else
			redirect_to :controller => 'users', :action => 'auth'
		end
	end

	def create
		if is_auth?
				@affiliate = Affiliate.create(affiliate_params)
				if @affiliate.errors.empty?
					redirect_to :controller => "affiliates", :action => "index"
				else
					render "new"
				end
		else
			redirect_to :controller => 'users', :action => 'auth'
		end
	end

	def edit
		if is_auth?
			@companies = Company.all
			@affiliate = Affiliate.find(params[:id])
		else
			redirect_to :controller => 'users', :action => 'auth'
		end
	end

	def update 
		if is_auth?
			@affiliate = Affiliate.find(params[:id])
			@affiliate.update_attributes(affiliate_params)
			if @affiliate.errors.empty?
				redirect_to :controller => "affiliates", :action => "index"
			else
				render "edit"
			end
		else
			redirect_to :controller => 'users', :action => 'auth'
		end
	end

	def destroy
		if is_auth?
			@affiliate = Affiliate.find(params[:id])
			@affiliate.is_deleted = true
			@affiliate.is_enabled = false
			@affiliate.name = "#{@affiliate.name}[deleted]"
			@affiliate.save
			redirect_to :controller => "affiliates", :action => "index"
		else
			redirect_to :controller => 'users', :action => 'auth'
		end
	end



private
	def affiliate_params
		params.require(:affiliate).permit(:name,:company_id,:is_enabled)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CanCan::ControllerAdditions
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  helper_method :is_auth?

  rescue_from CanCan::AccessDenied do |exception|
  	render :file => "#{Rails.root}/public/403.html", :status => 403, :layout => false
  end

  def is_auth?
  	@user = User.find_by_id(session[:user_id])
    !@user.nil?
  end
  def current_user

  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

	def index
		if is_auth?
			@companies = Company.all
		else
			redirect_to :controller => 'users', :action => 'auth'
		end
	end

	def show

	end

	def new

	end

	def edit

	end

	def create

	end

	def destroy

	end

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
	authorize_resource class: false
	
	def index
		if is_auth?
			@installations
			@statistics
			@header_title

	 		period = params[:query]
	 		if (period == "all" || period == nil)
	 			@header_title = "Amount"
	 			@installations = Installation.all
	 			@statistics = Statistic.order( date: :desc )
	 		elsif (period == "month")
	 			@header_title = "Last 30 days"
	 			@installations = Installation.where(created_at: 1.month.ago..Time.now)
	 			@statistics = Statistic.where(date: 1.month.ago..Time.now).order( date: :desc )
	 		end
	 		@translate_count = 0

	 		@statistics.each do |i|
	 			a = Affiliate.find_by_id(i.affiliate_id)
	 			next if a.is_deleted
	 			@translate_count += i[:count]
	 		end
		else
			redirect_to :controller => 'users', :action => 'auth'
		end
	end

	def create
		affiliate = Affiliate.find_by_name(params[:affiliate_name])
		if (affiliate.blank?)
			render status: 200, text: "fail"
		end

		installation = Installation.find_by_device_id( params[:device_id] )
		if (installation.blank?)
			Installation.create( affiliate_id: affiliate.id, device_id: params[:device_id] )
		end

		statistic = Statistic.find_by_date_and_affiliate_id( Date.today.to_s, affiliate.id )
		if (statistic.blank?)
			Statistic.create( { date: Date.today.to_s, count: params[:count], affiliate_id: affiliate.id } )
		else
			Statistic.where( affiliate_id: affiliate.id, date: Date.today.to_s).update_all( count: params[:count].to_i + statistic.count )
		end
		render status: 200, text: "success"
	end

	def get_data
		receive_company = params[:company]
		p receive_company
		if (!receive_company.blank?)
			company = Company.find_by_name(receive_company)
			p company
			json_reply = company.affiliates.to_json( :only => [:name,:is_enabled])
			json_reply = "{\"affiliates\":" + json_reply + "}"
			render status: 200, json: json_reply
		else
			render status: 200, text: "no data"
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def auth
		@user = User.find_by_id(session[:user_id])
		if (@user)
			redirect_to :controller => 'statistics', :action => 'index'
		else
			@user = User.new
			session[:return_to] ||= request.referrer
		end
	end

	def options

	end

	def check
		p params
		@user = User.find_by_login_and_password( params[:user][:login], params[:user][:password] )
		if (@user)
			session[:user_id] =  @user.id
			redirect_to :controller => 'statistics', :action => 'index'
		else
			session[:return_to] ||= request.referrer
			redirect_to session.delete(:return_to)
		end
	end

	def logout
		session[:user_id] = nil
		redirect_to :controller => 'users', :action => 'auth'
	end

	def toggle
		command = params[:command]
		if (command == "disable") 
			Affiliate.where( is_deleted: false ).update_all( is_enabled: false )
		elsif (command == "enable")
			Affiliate.where( is_deleted: false ).update_all( is_enabled: true)
		end
		redirect_to :controller => "affiliates", :action => "index"
	end
end

app/helpers/affiliates_helper.rb
module AffiliatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/affiliates/edit.html.erb
<div class="container">
	<%= form_for @affiliate, url: { action: "update" }, html: { class: "form-group" }  do |f| %>
<p> Name:</br> <%= f.text_field( :name, class: "form-control") %> </p>
<p> Company:</br> <%= f.select :company_id, @companies.map { |c| [c.name, c.id] }, {},  { :class => "form-control" } %> </p>
<div class="checkbox"><label><%= f.check_box :is_enabled %> Enabled </label> 
</div>
<div class="btn-group-horizontal">
	<%= submit_tag "Change", class: "btn btn-lg btn-primary btn-block" %>
	<%= link_to "Back", :back,  {class: "btn btn-lg btn-primary btn-block"} %>
</div>
<% end %>
</div>

app/views/affiliates/index.html.erb
<div class="row">
	<div class="col-md-9 col-md-offset-3 main">
		<h1 class="text-center">Affiliates</h1>
		<div class="table-responsive">
			<table id="data" class="table table-stripped">
				<tr>
					<th>Name</th>
					<th>Company</th>
					<th>Active</th>
					<th></th>
					<th></th>
				</tr>
				<% @affiliates.each do |a| %>
					<tr data-link="<%= edit_affiliate_path(a) %>">
						<td><%= a.name %> </td>
						<td><%= a.company.name %> </td>
						<td><%= a.is_enabled  %> </td>
						<td><%= button_to "Edit", edit_affiliate_path(a), :method => :get, :class => "btn btn-default" %> </td>
						<td><%= button_to "Delete", affiliate_path(a), :method => :delete, :class => "btn btn-default", data: { :confirm => "Are you sure?" } %> </td>
					</tr>
				<% end %>
			</table>
			<%= button_to "Add", new_affiliate_path, :method => :get, :class => "btn btn-primary custom pull-right" %> 
			<div class="btn group">
				<%= link_to "Disable All", {:controller => "users", :action => "toggle", :command => "disable"}, :class => "btn btn-danger custom", :role => "button" %>
				<%= link_to "Enable All", {:controller => "users", :action => "toggle", :command => "enable"}, :class => "btn btn-success custom", :role=> "button" %>
			</div>
		</div>
	</div>
</div>

app/views/affiliates/new.html.erb
new.html.erb

app/views/companies/index.html.erb
<div class="row">
<div class="col-md-9 col-md-offset-3 main">
	<h1 class="text-center">Companies</h1>
	<div class="table-responsive">
	<table class="table table-stripped">
		<tr>
			<th>Name</th>
		</tr>
		<% @companies.each do |c| %>
			<tr>
				<td><%= c.name %> </td>
			</tr>
		<% end %>
	</table>
</div>
</div>
  <div class="navbar navbar-inverse navbar-fixed-bottom">
  	<div class="btn-group">
  		<button type="button" class="btn btn-primary">Add</button>
  		<button type="button" class="btn btn-primary">Edit</button>
  		<button type="button" class="btn btn-primary">Remove</button>
  	</div>
  </div>
</div>

app/views/companies/new.html.erb
new.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Statistic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse">
  		<div class="container-fluid">
  			<% if is_auth? %>
  				<ul class="nav navbar-nav">

            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="">Statistic <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Amount", :controller => "statistics", :action => "index", :query => "all" %></li>
                <li><%= link_to "Last 30 days", :controller => "statistics", :action => "index", :query => "month" %></li>
              </ul>
            </li>


            <li><%= link_to "Affiliates", :controller => "affiliates", :action => "index" %></li>
  					<li><%= link_to "Companies", :controller => "companies", :action => "index" %></li>
  				</ul>
  				<ul class="nav navbar-nav navbar-right">
  					<li><%= link_to "Log out", :controller=> "users", :action => "logout" %></li>
  				</ul>
  			<% end %>

  		</div>
  </div>
  <div class="container-fluid">
		<%= yield %>
  </div>
</body>
</html>

app/views/statistics/index.html.erb
<div class="row">
	<div class="col-md-9 col-md-offset-3 main">
		<h1 class="text-center"><%= @header_title %> </h1>
		<div class="table-responsive">
			<table id="data" class="table table-stripped">
				<tr>
					<th>Date</th>
					<th>Affiliate</th>
					<th>Count</th>
				</tr>
				<% @statistics.each do |s| %>
					<% a = Affiliate.find_by_id(s.affiliate_id) %>
					<% next if a.is_deleted || s.count == 0 %>
					<tr>
						<td><%= s.date %> </td>
						<td><%= a.name %> </td>
						<td><%= s.count %> </td>
					</tr>
				<% end %>
			</table>
		</div>
		<p class="text-right">Total number of installations: <%= @installations.count %> </p>
		<p class="text-right">Total number of translated URL: <%= @translate_count %> </p>
	</div>
</div>

app/views/users/auth.html.erb
<div class="container">
	<%= form_for @user, url: { action: "check" }, html: { class: "form-signin" }  do |f| %>
<p> Name:</br> <%= f.text_field( :login, class: "form-control") %> </p>
<p> Password:</br> <%= f.password_field(:password, class: "form-control") %> </p>
<p> <%= submit_tag "Log in", class: "btn btn-lg btn-primary btn-block" %> </p>
<% end %>
</div>